export const DMA_REGISTRY = [
    // united states
    { dmaId: 212, name: 'Abilene - Sweetwater', country: 'USA' },
    { dmaId: 213, name: 'Albany - Schenectady - Troy', country: 'USA' },
    { dmaId: 215, name: 'Albuquerque - Santa Fe', country: 'USA' },
    { dmaId: 216, name: 'Alexandria', country: 'USA' },
    { dmaId: 217, name: 'Alpena', country: 'USA' },
    { dmaId: 218, name: 'Amarillo', country: 'USA' },
    { dmaId: 219, name: 'Anchorage', country: 'USA' },
    { dmaId: 220, name: 'Atlanta', country: 'USA' },
    { dmaId: 221, name: 'Augusta', country: 'USA' },
    { dmaId: 222, name: 'Austin', country: 'USA' },
    { dmaId: 223, name: 'Bakersfield', country: 'USA' },
    { dmaId: 224, name: 'Baltimore', country: 'USA' },
    { dmaId: 225, name: 'Bangor', country: 'USA' },
    { dmaId: 226, name: 'Baton Rouge', country: 'USA' },
    { dmaId: 227, name: 'Beaumont - Port Arthur', country: 'USA' },
    { dmaId: 228, name: 'Bend', country: 'USA' },
    { dmaId: 229, name: 'Billings', country: 'USA' },
    { dmaId: 230, name: 'Biloxi - Gulfport', country: 'USA' },
    { dmaId: 231, name: 'Binghamton', country: 'USA' },
    { dmaId: 237, name: 'Buffalo', country: 'USA' },
    { dmaId: 245, name: 'Charlotte', country: 'USA' },
    { dmaId: 246, name: 'Charlottesville', country: 'USA' },
    { dmaId: 249, name: 'Chicago', country: 'USA' },
    { dmaId: 251, name: 'Cincinnati', country: 'USA' },
    { dmaId: 253, name: 'Cleveland', country: 'USA' },
    { dmaId: 263, name: 'Dayton', country: 'USA' },
    { dmaId: 264, name: 'Denver', country: 'USA' },
    { dmaId: 266, name: 'Detroit', country: 'USA' },
    { dmaId: 267, name: 'Dothan', country: 'USA' },
    { dmaId: 269, name: 'El Paso', country: 'USA' },
    { dmaId: 274, name: 'Evansville', country: 'USA' },
    { dmaId: 278, name: 'Florence - Myrtle Beach', country: 'USA' },
    { dmaId: 299, name: 'Honolulu', country: 'USA' },
    { dmaId: 300, name: 'Houston', country: 'USA' },
    { dmaId: 303, name: 'Indianapolis', country: 'USA' },
    { dmaId: 306, name: 'Jacksonville', country: 'USA' },
    { dmaId: 311, name: 'Kansas City', country: 'USA' },
    { dmaId: 319, name: 'Las Vegas', country: 'USA' },
    { dmaId: 324, name: 'Los Angeles', country: 'USA' },
    { dmaId: 332, name: 'Memphis', country: 'USA' },
    { dmaId: 335, name: 'Milwaukee', country: 'USA' },
    { dmaId: 343, name: 'Nashville', country: 'USA' },
    { dmaId: 344, name: 'New Orleans', country: 'USA' },
    { dmaId: 345, name: 'New York', country: 'USA' },
    { dmaId: 349, name: 'Oklahoma City', country: 'USA' },
    { dmaId: 354, name: 'Palm Springs', country: 'USA' },
    { dmaId: 359, name: 'Phoenix', country: 'USA' },
    { dmaId: 360, name: 'Pittsburgh', country: 'USA' },
    { dmaId: 362, name: 'Portland, OR', country: 'USA' },
    { dmaId: 378, name: 'Salt Lake City', country: 'USA' },
    { dmaId: 380, name: 'San Antonio', country: 'USA' },
    { dmaId: 381, name: 'San Diego', country: 'USA' },
    { dmaId: 384, name: 'Savannah', country: 'USA' },
    { dmaId: 388, name: 'Sioux City', country: 'USA' },
    { dmaId: 398, name: 'Toledo', country: 'USA' },
    { dmaId: 403, name: 'Tulsa', country: 'USA' },

    // canada
    { dmaId: 516, name: 'Nova Scotia', country: 'Canada' },
    { dmaId: 522, name: 'Montreal', country: 'Canada' },
    { dmaId: 527, name: 'Toronto', country: 'Canada' },
    { dmaId: 528, name: 'Vancouver', country: 'Canada' },

    // europe
    { dmaId: 602, name: 'London', country: 'England' },

    // mexico
    { dmaId: 802, name: 'Mexico City', country: 'Mexico' },
    { dmaId: 803, name: 'Monterrey', country: 'Mexico' },
    { dmaId: 804, name: 'Guadalajara', country: 'Mexico' },
];