const DMA_REGISTRY = [
    // united states
    { dmaId: 212, name: 'Abilene - Sweetwater', country: 'USA' },
    { dmaId: 213, name: 'Albany - Schenectady - Troy', country: 'USA' },
    { dmaId: 214, name: 'Albany, GA', country: 'USA' },
    { dmaId: 215, name: 'Albuquerque - Santa Fe', country: 'USA' },
    { dmaId: 216, name: 'Alexandria', country: 'USA' },
    { dmaId: 217, name: 'Alpena', country: 'USA' },
    { dmaId: 218, name: 'Amarillo', country: 'USA' },
    { dmaId: 219, name: 'Anchorage', country: 'USA' },
    { dmaId: 220, name: 'Atlanta', country: 'USA' },
    { dmaId: 221, name: 'Augusta', country: 'USA' },
    { dmaId: 222, name: 'Austin', country: 'USA' },
    { dmaId: 223, name: 'Bakersfield', country: 'USA' },
    { dmaId: 224, name: 'Baltimore', country: 'USA' },
    { dmaId: 225, name: 'Bangor', country: 'USA' },
    { dmaId: 226, name: 'Baton Rouge', country: 'USA' },
    { dmaId: 227, name: 'Beaumont - Port Arthur', country: 'USA' },
    { dmaId: 228, name: 'Bend', country: 'USA' },
    { dmaId: 229, name: 'Billings', country: 'USA' },
    { dmaId: 230, name: 'Biloxi - Gulfport', country: 'USA' },
    { dmaId: 231, name: 'Binghamton', country: 'USA' },
    { dmaId: 232, name: 'Birmingham(Anniston and Tuscaloosa)', country: 'USA' },
    { dmaId: 233, name: 'Bluefield - Beckley - Oak Hill', country: 'USA' },
    { dmaId: 234, name: 'Boise', country: 'USA' },
    { dmaId: 235, name: 'Boston(Manchester)', country: 'USA' },
    { dmaId: 236, name: "Bowling Green", country: 'USA' },
    { dmaId: 237, name: 'Buffalo', country: 'USA' },
    { dmaId: 238, name: 'Burlington - Plattsburgh', country: 'USA' },
    { dmaId: 239, name: 'Butte - Bozeman', country: 'USA' },
    { dmaId: 240, name: 'Casper - Riverton', country: 'USA' },
    { dmaId: 241, name: 'Cedar Rapids - Waterloo & Dubuque', country: 'USA' },
    { dmaId: 242, name: 'Champaign & Springfield - Decatur', country: 'USA' },
    { dmaId: 243, name: 'Charleston, SC', country: 'USA' },
    { dmaId: 244, name: 'Charleston - Huntington', country: 'USA' },
    { dmaId: 245, name: 'Charlotte', country: 'USA' },
    { dmaId: 246, name: 'Charlottesville', country: 'USA' },
    { dmaId: 247, name: 'Chattanooga', country: 'USA' },
    { dmaId: 248, name: 'Cheyenne - Scottsbluff', country: 'USA' },
    { dmaId: 249, name: 'Chicago', country: 'USA' },
    { dmaId: 250, name: 'Chico - Redding', country: 'USA' },
    { dmaId: 251, name: 'Cincinnati', country: 'USA' },
    { dmaId: 252, name: 'Clarksburg - Weston', country: 'USA' },
    { dmaId: 253, name: 'Cleveland', country: 'USA' },
    { dmaId: 254, name: 'Colorado Springs - Pueblo', country: 'USA' },
    { dmaId: 255, name: 'Columbia - Jefferson City', country: 'USA' },
    { dmaId: 256, name: 'Columbia, SC', country: 'USA' },
    { dmaId: 257, name: 'Columbus - Tupelo - West Point', country: 'USA' },
    { dmaId: 258, name: 'Columbus, GA', country: 'USA' },
    { dmaId: 259, name: 'Columbus, OH', country: 'USA' },
    { dmaId: 260, name: 'Corpus Christi', country: 'USA' },
    { dmaId: 261, name: 'Dallas - Fort Worth', country: 'USA' },
    { dmaId: 262, name: 'Davenport - Rock Island - Moline', country: 'USA' },
    { dmaId: 263, name: 'Dayton', country: 'USA' },
    { dmaId: 264, name: 'Denver', country: 'USA' },
    { dmaId: 265, name: 'Des Moines - Ames', country: 'USA' },
    { dmaId: 266, name: 'Detroit', country: 'USA' },
    { dmaId: 267, name: 'Dothan', country: 'USA' },
    { dmaId: 268, name: 'Duluth - Superior', country: 'USA' },
    { dmaId: 269, name: 'El Paso', country: 'USA' },
    { dmaId: 270, name: 'Elmira', country: 'USA' },
    { dmaId: 271, name: 'Erie', country: 'USA' },
    { dmaId: 272, name: 'Eugene', country: 'USA' },
    { dmaId: 273, name: 'Eureka', country: 'USA' },
    { dmaId: 274, name: 'Evansville', country: 'USA' },
    { dmaId: 275, name: 'Fairbanks', country: 'USA' },
    { dmaId: 276, name: 'Fargo - Valley City', country: 'USA' },
    { dmaId: 277, name: 'Flint - Saginaw - Bay City', country: 'USA' },
    { dmaId: 278, name: 'Florence - Myrtle Beach', country: 'USA' },
    { dmaId: 279, name: 'Fort Myers - Naples', country: 'USA' },
    { dmaId: 280, name: 'Fort Smith - Fayetteville - Springdale - Rogers', country: 'USA' },
    { dmaId: 281, name: 'Fort Wayne', country: 'USA' },
    { dmaId: 282, name: 'Fresno - Visalia', country: 'USA' },
    { dmaId: 283, name: 'Gainesville', country: 'USA' },
    { dmaId: 284, name: 'Glendive', country: 'USA' },
    { dmaId: 285, name: 'Grand Junction - Montrose', country: 'USA' },
    { dmaId: 286, name: 'Grand Rapids - Kalamazoo - Battle Creek', country: 'USA' },
    { dmaId: 287, name: 'Great Falls', country: 'USA' },
    { dmaId: 288, name: 'Green Bay - Appleton', country: 'USA' },
    { dmaId: 289, name: 'Greensboro - High Point - Winston - Salem', country: 'USA' },
    { dmaId: 290, name: 'Greenville - New Bern - Washington', country: 'USA' },
    { dmaId: 291, name: 'Greenville - Spartansburg - Asheville - Anderson', country: 'USA' },
    { dmaId: 292, name: 'Greenwood - Greenville', country: 'USA' },
    { dmaId: 293, name: 'Harlingen - Weslaco - Brownsville - McAllen', country: 'USA' },
    { dmaId: 294, name: 'Harrisburg - Lancaster - Lebanon - York', country: 'USA' },
    { dmaId: 295, name: 'Harrisonburg', country: 'USA' },
    { dmaId: 296, name: 'Hartford & New Haven', country: 'USA' },
    { dmaId: 297, name: 'Hattiesburg - Laurel', country: 'USA' },
    { dmaId: 298, name: 'Helena', country: 'USA' },
    { dmaId: 299, name: 'Honolulu', country: 'USA' },
    { dmaId: 300, name: 'Houston', country: 'USA' },
    { dmaId: 301, name: 'Huntsville - Decatur(Florence)' },
    { dmaId: 302, name: 'Idaho Falls - Pocatello' },
    { dmaId: 303, name: 'Indianapolis', country: 'USA' },
    { dmaId: 304, name: 'Jackson, MS', country: 'USA' },
    { dmaId: 305, name: 'Jackson, TN', country: 'USA' },
    { dmaId: 306, name: 'Jacksonville', country: 'USA' },
    { dmaId: 307, name: 'Johnstown - Altoona', country: 'USA' },
    { dmaId: 308, name: 'Jonesboro', country: 'USA' },
    { dmaId: 309, name: 'Joplin - Pittsburg', country: 'USA' },
    { dmaId: 310, name: 'Juneau', country: 'USA' },
    { dmaId: 311, name: 'Kansas City', country: 'USA' },
    { dmaId: 312, name: 'Knoxville', country: 'USA' },
    { dmaId: 313, name: 'La Crosse - Eau Claire', country: 'USA' },
    { dmaId: 314, name: 'Lafayette, IN', country: 'USA' },
    { dmaId: 315, name: 'Lafayette, LA', country: 'USA' },
    { dmaId: 316, name: 'Lake Charles', country: 'USA' },
    { dmaId: 317, name: 'Lansing', country: 'USA' },
    { dmaId: 318, name: 'Laredo', country: 'USA' },
    { dmaId: 319, name: 'Las Vegas', country: 'USA' },
    { dmaId: 320, name: 'Lexington', country: 'USA' },
    { dmaId: 321, name: 'Lima', country: 'USA' },
    { dmaId: 322, name: 'Lincoln & Hastings - Kearney' },
    { dmaId: 323, name: 'Little Rock - Pine Bluff' },
    { dmaId: 324, name: 'Los Angeles', country: 'USA' },
    { dmaId: 325, name: 'Louisville', country: 'USA' },
    { dmaId: 326, name: 'Lubbock', country: 'USA' },
    { dmaId: 327, name: 'Macon', country: 'USA' },
    { dmaId: 328, name: 'Madison', country: 'USA' },
    { dmaId: 329, name: 'Mankato', country: 'USA' },
    { dmaId: 330, name: 'Marquette', country: 'USA' },
    { dmaId: 331, name: 'Medford - Klamath Falls', country: 'USA' },
    { dmaId: 332, name: 'Memphis', country: 'USA' },
    { dmaId: 333, name: 'Meridian', country: 'USA' },
    { dmaId: 334, name: 'Miami - Fort Lauderdale', country: 'USA' },
    { dmaId: 335, name: 'Milwaukee', country: 'USA' },
    { dmaId: 336, name: 'Minneapolis - Saint Paul', country: 'USA' },
    { dmaId: 337, name: 'Minot - Bismarck - Dickinson', country: 'USA' },
    { dmaId: 338, name: 'Missoula', country: 'USA' },
    { dmaId: 339, name: 'Mobile - Pensacola(Fort Walton Beach)', country: 'USA' },
    { dmaId: 340, name: 'Monroe - El Dorado', country: 'USA' },
    { dmaId: 341, name: 'Monterey - Salinas', country: 'USA' },
    { dmaId: 342, name: 'Montgomery(Selma)', country: 'USA' },
    { dmaId: 343, name: 'Nashville', country: 'USA' },
    { dmaId: 344, name: 'New Orleans', country: 'USA' },
    { dmaId: 345, name: 'New York', country: 'USA' },
    { dmaId: 346, name: 'Norfolk - Portsmouth - Newport News', country: 'USA' },
    { dmaId: 347, name: 'North Platte', country: 'USA' },
    { dmaId: 348, name: 'Odessa - Midland', country: 'USA' },
    { dmaId: 349, name: 'Oklahoma City', country: 'USA' },
    { dmaId: 350, name: 'Omaha', country: 'USA' },
    { dmaId: 351, name: 'Orlando - Daytona Beach - Melbourne', country: 'USA' },
    { dmaId: 352, name: 'Ottumwa - Kirksville', country: 'USA' },
    { dmaId: 353, name: 'Paducah - Cape Girardeau - Harrisburg - Mt Vernon', country: 'USA' },
    { dmaId: 354, name: 'Palm Springs', country: 'USA' },
    { dmaId: 355, name: 'Panama City', country: 'USA' },
    { dmaId: 356, name: 'Parkersburg', country: 'USA' },
    { dmaId: 357, name: 'Peoria - Bloomington', country: 'USA' },
    { dmaId: 358, name: 'Philadelphia', country: 'USA' },
    { dmaId: 359, name: 'Phoenix', country: 'USA' },
    { dmaId: 360, name: 'Pittsburgh', country: 'USA' },
    { dmaId: 361, name: 'Portland - Auburn', country: 'USA' },
    { dmaId: 362, name: 'Portland, OR', country: 'USA' },
    { dmaId: 363, name: 'Presque Isle', country: 'USA' },
    { dmaId: 364, name: 'Providence - New Bedford', country: 'USA' },
    { dmaId: 365, name: 'Quincy - Hannibal - Keokuk', country: 'USA' },
    { dmaId: 366, name: 'Raleigh - Durham (Fayetteville)', country: 'USA' },
    { dmaId: 367, name: 'Rapid City', country: 'USA' },
    { dmaId: 368, name: 'Reno', country: 'USA' },
    { dmaId: 369, name: 'Richmond - Petersburg', country: 'USA' },
    { dmaId: 370, name: 'Roanoke - Lynchburg', country: 'USA' },
    { dmaId: 371, name: 'Rochester - Mason City - Austin', country: 'USA' },
    { dmaId: 372, name: 'Rochester, NY', country: 'USA' },
    { dmaId: 373, name: 'Rockford', country: 'USA' },
    { dmaId: 374, name: 'Sacramento - Stockton - Modesto', country: 'USA' },
    { dmaId: 375, name: 'Saint Joseph', country: 'USA' },
    { dmaId: 376, name: 'Saint Louis', country: 'USA' },
    { dmaId: 377, name: 'Salisbury', country: 'USA' },
    { dmaId: 378, name: 'Salt Lake City', country: 'USA' },
    { dmaId: 379, name: 'San Angelo', country: 'USA' },
    { dmaId: 380, name: 'San Antonio', country: 'USA' },
    { dmaId: 381, name: 'San Diego', country: 'USA' },
    { dmaId: 382, name: 'San Francisco - Oakland - San Jose', country: 'USA' },
    { dmaId: 383, name: 'Santa Barbara - Santa Maria - San Luis Obispo', country: 'USA' },
    { dmaId: 384, name: 'Savannah', country: 'USA' },
    { dmaId: 385, name: 'Seattle - Tacoma', country: 'USA' },
    { dmaId: 386, name: 'Sherman - Ada', country: 'USA' },
    { dmaId: 387, name: 'Shreveport', country: 'USA' },
    { dmaId: 388, name: 'Sioux City', country: 'USA' },
    { dmaId: 389, name: 'Sioux Falls (Mitchell)', country: 'USA' },
    { dmaId: 390, name: 'South Bend - Elkhart', country: 'USA' },
    { dmaId: 391, name: 'Spokane', country: 'USA' },
    { dmaId: 392, name: 'Springfield - Holyoke', country: 'USA' },
    { dmaId: 393, name: 'Springfield, MO', country: 'USA' },
    { dmaId: 394, name: 'Syracuse', country: 'USA' },
    { dmaId: 395, name: 'Tallahassee - Thomasville', country: 'USA' },
    { dmaId: 396, name: 'Tampa - Saint Petersburg (Sarasota)', country: 'USA' },
    { dmaId: 397, name: 'Terre Haute', country: 'USA' },
    { dmaId: 398, name: 'Toledo', country: 'USA' },
    { dmaId: 399, name: 'Topeka', country: 'USA' },
    { dmaId: 400, name: 'Traverse City - Cadillac', country: 'USA' },
    { dmaId: 401, name: 'Tri-Cities, TN - VA', country: 'USA' },
    { dmaId: 402, name: 'Tucson (Sierra Vista)', country: 'USA' },
    { dmaId: 403, name: 'Tulsa', country: 'USA' },
    { dmaId: 404, name: 'Twin Falls', country: 'USA' },
    { dmaId: 405, name: 'Tyler - Longview (Lufkin & Nacogdoches)', country: 'USA' },
    { dmaId: 406, name: 'Utica', country: 'USA' },
    { dmaId: 407, name: 'Victoria', country: 'USA' },
    { dmaId: 408, name: 'Waco - Temple - Bryan', country: 'USA' },
    { dmaId: 409, name: 'Washington DC (Hagerstown)', country: 'USA' },
    { dmaId: 410, name: 'Watertown', country: 'USA' },
    { dmaId: 411, name: 'Wausau - Rhinelander', country: 'USA' },
    { dmaId: 412, name: 'West Palm Beach - Fort Pierce', country: 'USA' },
    { dmaId: 413, name: 'Wheeling - Steubenville', country: 'USA' },
    { dmaId: 414, name: 'Wichita - Hutchinson', country: 'USA' },
    { dmaId: 415, name: 'Wichita Falls & Lawton', country: 'USA' },
    { dmaId: 416, name: 'Wilkes-Barre - Scranton', country: 'USA' },
    { dmaId: 417, name: 'Wilmington', country: 'USA' },
    { dmaId: 418, name: 'Yakima - Pasco - Richland - Kennewick', country: 'USA' },
    { dmaId: 419, name: 'Youngstown', country: 'USA' },
    { dmaId: 420, name: 'Yuma - El Centro', country: 'USA' },
    { dmaId: 421, name: 'Zanesville', country: 'USA' },
    { dmaId: 422, name: 'Northern New Jersey', country: 'USA' },

    // canada
    { dmaId: 500, name: 'All of Canada', country: 'Canada' },
    { dmaId: 501, name: 'Barrie - Orillia', country: 'Canada' },
    { dmaId: 502, name: 'Belleville - Peterborough', country: 'Canada' },
    { dmaId: 503, name: 'Owen Sound', country: 'Canada' },
    { dmaId: 504, name: 'Burnaby - New Westminster - Surrey', country: 'Canada' },
    { dmaId: 505, name: 'Calgary - Banff', country: 'Canada' },
    { dmaId: 506, name: 'Edmonton', country: 'Canada' },
    { dmaId: 507, name: 'Fraser Valley', country: 'Canada' },
    { dmaId: 508, name: 'Hamilton - Niagara', country: 'Canada' },
    { dmaId: 509, name: 'Kitchener - Waterloo', country: 'Canada' },
    { dmaId: 510, name: 'London - Sarnia', country: 'Canada' },
    { dmaId: 511, name: 'Mississauga - Oakville', country: 'Canada' },
    { dmaId: 512, name: 'Newfoundland', country: 'Canada' },
    { dmaId: 513, name: 'Northwest Territories', country: 'Canada' },
    { dmaId: 514, name: 'New Brunswick', country: 'Canada' },
    { dmaId: 515, name: 'Northern Ontario', country: 'Canada' },
    { dmaId: 516, name: 'Nova Scotia', country: 'Canada' },
    { dmaId: 517, name: 'Nunavut', country: 'Canada' },
    { dmaId: 518, name: 'Okanagan - Kootenays', country: 'Canada' },
    { dmaId: 519, name: 'Ottawa - Gatineau', country: 'Canada' },
    { dmaId: 520, name: 'Prince Edward Island', country: 'Canada' },
    { dmaId: 521, name: 'Prince George - North', country: 'Canada' },
    { dmaId: 522, name: 'Montreal', country: 'Canada' },
    { dmaId: 523, name: 'Red Deer', country: 'Canada' },
    { dmaId: 524, name: 'Saskatchewan', country: 'Canada' },
    { dmaId: 527, name: 'Toronto', country: 'Canada' },
    { dmaId: 528, name: 'Vancouver', country: 'Canada' },
    { dmaId: 529, name: 'Sunshine Coast - Islands', country: 'Canada' },
    { dmaId: 530, name: 'Winnipeg - Brandon', country: 'Canada' },
    { dmaId: 531, name: 'Yukon', country: 'Canada' },

    // europe part 1
    { dmaId: 602, name: 'London', country: 'England' },
    { dmaId: 603, name: 'South', country: 'England' },
    { dmaId: 604, name: 'Midlands and Central', country: 'UK' },
    { dmaId: 605, name: 'Wales and North West', country: 'UK' },
    { dmaId: 606, name: 'North and North East', country: 'UK' },
    { dmaId: 607, name: 'Scotland', country: 'Scotland' },
    { dmaId: 608, name: 'Ireland', country: 'Ireland' },
    { dmaId: 609, name: 'Northern Ireland', country: 'Ireland' },
    { dmaId: 610, name: 'Germany', country: 'Germany' },
    { dmaId: 611, name: 'Netherlands', country: 'Netherlands' },
    { dmaId: 612, name: 'Sweden', country: 'Sweden' },
    { dmaId: 613, name: 'Turkey', country: 'Turkey' },

    // australia
    { dmaId: 701, name: 'Australia', country: 'Australia' },
    { dmaId: 702, name: 'New South Wales/Australian Capital Territory', country: 'Australia' },
    { dmaId: 703, name: 'Queensland', country: 'Australia' },
    { dmaId: 704, name: 'Western Australia', country: 'Australia' },
    { dmaId: 705, name: 'Victoria/Tasmania', country: 'Australia' },
    { dmaId: 750, name: 'All of New Zealand', country: 'New Zealand' },
    { dmaId: 751, name: 'North Island', country: 'New Zealand' },
    { dmaId: 752, name: 'South Island', country: 'New Zealand' },



    // mexico
    { dmaId: 801, name: 'Mexico', country: 'Mexico' },
    { dmaId: 802, name: 'Mexico City', country: 'Mexico' },
    { dmaId: 803, name: 'Monterrey', country: 'Mexico' },
    { dmaId: 804, name: 'Guadalajara', country: 'Mexico' },

    // spain (europe part 2)
    { dmaId: 901, name: 'Spain', country: 'Spain' },
    { dmaId: 902, name: 'Barcelona', country: 'Spain' },
    { dmaId: 903, name: 'Madrid', country: 'Spain' },
];

module.exports = DMA_REGISTRY;